variable "runner_platform" {
    nullable = false
    type = string
    description = "Runner platform hosting ARC and runners. Possible values ACA (Azure Container Apps), ECS (Elastic Container Service) and GCR (Google Cloud Run)"
    validation {
     condition     = can(regex("^(ACA|ECR|GCR)$", upper(var.runner_platform)))
     error_message = "Runner platform has to be either ACA, ECR or GCR (case insensitive)."
   }
}

# Variables generated by terraform-variable-collector start
variable "PAT" {
  type = any
  description = "Github PAT with Actions:Read and Admin:Read+Write scopes (Defined in: modules/azure-container-apps, modules/elastic-container-service, modules/google-cloud-run)"
}

variable "aca_location_486B7D73" {
  type = any
  description = "Location where to provision resources to (Defined in: modules/azure-container-apps)"
}

variable "github_config_url" {
  type = any
  description = "Github URL where runners should register to. Format https://<GitHub host>/<your_enterprise/org/repo> (Defined in: modules/azure-container-apps, modules/elastic-container-service, modules/google-cloud-run)"
}

# Variables generated by terraform-variable-collector end
